### ISSUE TITLE
[BUG] 显示被封禁，但是我并没有做什么

### ISSUE THREAD

**Issue by Erebus-qie** [nekoaoxiang/BiliRoamingX#9]
### 系统版本

origin os 4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.14.0

### 问题描述

显示账号已被封禁，日期为2077年1月1日
但是我并没有做什么，只是在刷视频
莫非作者大大吃律师函了？

### 复现步骤

1.打开
2.刷视频
3.弹出封禁
4.退出
5.打开
6.显示初次安装时弹出的通知
7.设置
8.重启
9.显示初次安装时弹出的通知，设置无效

### 日志

无法调试，退出重启后显示初次安装时弹出的通知，设置无效

### 截图或录屏

![Screenshot_20241031_185537](https://github.com/user-attachments/assets/9dddfd77-50af-4416-90e3-ad2cbb09252f)

**Comment by nekoaoxiang** [comment]
https://t.me/c/1546664044/848

**Comment by Erebus-qie** [comment]
很抱歉，我尝试了很多次，但是一直登不上tg，能否请您转述一下？或者您把详细的信息发到我的邮箱？（erebus.qie@qq.com或erebus@111.com）谢谢您

**Comment by Xiaoqianghepipi** [comment]
> 很抱歉，我尝试了很多次，但是一直登不上tg，能否请您转述一下？或者您把详细的信息发到我的邮箱？（[erebus.qie@qq.com](mailto:erebus.qie@qq.com)或[erebus@111.com](mailto:erebus@111.com)）谢谢您

当时是有人大量宣传，然后作者紧急封禁了所有用户

**Comment by Erebus-qie** [comment]
好的，谢谢您
